### ISSUE TITLE
Add support for Unix-domain sockets

### ISSUE THREAD

**Issue by bradwilson** [fluent/fluent-logger-node#96]
I am using an environment where our fluentd server is exposed via Unix-domain socket rather than a TCP socket. I looked at issue #30 which was closed after a work-around was given. I'd like for this support to be first class rather than forking and patching myself.

Is there interest in this? I can submit a PR if so. FWIW, the suggested fix in #30 isn't right for general usage, because it changes the default value of the `port` field; a separate `unixSocket` field or something similar seems like it would be a clearer option.

**Comment by okkez** [comment]
I've added `path` option in https://github.com/fluent/fluent-logger-node/commit/ae093f4a2a084104d219bb4f87bf52c8fa47a460 instead of changing the default value of `port` option.
Have you checked it?
See also https://github.com/fluent/fluent-logger-node#options

Could you create PR to improve Unix domain socket support?

**Comment by okkez** [comment]
Unix domain socket has been already supported. Closing.
